db-uri = "postgresql://localhost:5432/shiprag"
db-schema = "public"
db-anon-role = "eonl"
server-port = 54321
openapi-mode = "ignore-privileges"
db-pool = 10
db-pool-timeout = 10
# JWT secret for local dev - any string works for validation
jwt-secret = "local-dev-secret-that-is-long-enough-for-hs256"
